version: '3'

services:
  root:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: admin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
  intermediate:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: admin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
    ports:
      - 8201:8201
    cap_add:
      - IPC_LOCK
